<a href="https://colab.research.google.com/github/sreent/data-management-intro/blob/main/Hand-On%20SQL%20Demonstrations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Setting Up MySQL Environment

In [1]:
# install and start mysql server
!apt -qq update > /dev/null
!apt -y -qq install mysql-server > /dev/null
!/etc/init.d/mysql restart > /dev/null

# mount gdrive, required for downloaded dataset (or sql data dump)
import os

# install gdown, required for download file from GDrive
!pip -q install gdown
import gdown

# URL for our dataset, suicide-records.csv
URL = "https://drive.google.com/file/d/1PHuYietO9nXwO_BdoWvtNtIE-nmDjQYN/view?usp=sharing"
FILE_PATH = "https://drive.google.com/uc?export=download&id=" + URL.split("/")[-2]

# download and upload the csv data to GDRIVE and place inside GD_PROJECT_HOME/data folder.
# in case of Suicide Records, it will be at databases/suicides/data
gdown.download(FILE_PATH, "library-schema-mysql.sql", quiet=True)


# restore the employees sample database from the dump data
!mysql -t < library-schema-mysql.sql > /dev/null


# create a database user and grant access to the employees database
!mysql -e "CREATE USER IF NOT EXISTS 'francis'@'localhost' IDENTIFIED WITH mysql_native_password BY 'california';"
!mysql -e "GRANT ALL PRIVILEGES ON library.* TO 'francis'@'localhost';"

# install sqlalchemy
!pip install -q sqlalchemy==2.0.20
# install sql magic, required for running sql commands in jupyter notebook
!pip install -q ipython-sql==0.5.0
# install mysql python connector
!pip install -q pymysql==1.1.0

# enable sql magic in the notebook
%reload_ext sql

# queries are returned in the pandas format
%config SqlMagic.autopandas=True

# maximum # of rows to be rendered
import pandas as pd
pd.set_option('display.max_rows', 10)

# connect to the hr database
%sql mysql+pymysql://francis:california@localhost/library

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.


WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

su: warning: cannot change directory to /nonexistent: No such file or directory
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 21.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 8.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 1.4 MB/s eta 0:00:00

## Try It Yourself

In [ ]:
%%sql
# Insert Your Code Here
SELECT *
FROM Books;

 * mysql+pymysql://francis:***@localhost/library
10 rows affected.

,BookID,Title,Author,Genre,PublishedYear
0,101,Journey Through SQL,A. Coder,Technology,2015
1,102,The History of Databases,D. Base,Education,2018
2,103,Adventures in Coding,P. Programmer,Fiction,2020
3,104,Exploring Data Science,A. Coder,Science,2021
4,105,Fundamentals of Database Design,D. Base,Technology,2019
5,106,The World of Fictional Programming,P. Programmer,Sci-Fi,2022
6,107,Gardening for Beginners,G. Green,Hobby,2017
7,108,Advanced Gardening Techniques,G. Green,Non-Fiction,2020
8,109,Mysteries of the Universe,S. Hawking,Science,2019
9,110,Philosophy and Science,S. Hawking,Philosophy,2021